A <%= @exception.class %> occurred in <%= exception_source %>:

  <%= @exception.message %>
  <%= @backtrace.first %>

<%= @sections.map { |section| render_section(section) }.join %>
